name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: KtLint Check
        run: ./gradlew ktlintCheck
      - name: Kover
        run: ./gradlew koverVerify
      - name: Assemble
        run: ./gradlew build
